In [7]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings

In [8]:
df = pd.read_csv('train.txt',sep = ';',header =None,names =['text','emotion'])

In [9]:
df.head()

                                                text  emotion
0                            i didnt feel humiliated  sadness
1  i can go from feeling so hopeless to so damned...  sadness
2   im grabbing a minute to post i feel greedy wrong    anger
3  i am ever feeling nostalgic about the fireplac...     love
4                               i am feeling grouchy    anger

In [10]:
df.isnull().sum()

text       0
emotion    0
dtype: int64

In [11]:
unique_emotions= df['emotion'].unique()
emotion_numbers= {}
i = 0
for emo in unique_emotions:
  emotion_numbers[emo] = i
  i+=1

df['emotion']= df['emotion'].map(emotion_numbers)

In [12]:
df

                                                    text  emotion
0                                i didnt feel humiliated        0
1      i can go from feeling so hopeless to so damned...        0
2       im grabbing a minute to post i feel greedy wrong        1
3      i am ever feeling nostalgic about the fireplac...        2
4                                   i am feeling grouchy        1
...                                                  ...      ...
15995  i just had a very brief time in the beanbag an...        0
15996  i am now turning and i feel pathetic that i am...        0
15997                     i feel strong and good overall        5
15998  i feel like this was such a rude comment and i...        1
15999  i know a lot but i feel so stupid because i ca...        0

[16000 rows x 2 columns]

In [13]:
df['text'] = df['text'].apply(lambda x : x.lower())

In [14]:
import string
def remove_punctuation(text):
  return text.translate(str.maketrans('','',string.punctuation))

In [15]:
df['text'] = df['text'].apply(lambda x : remove_punctuation(x))

In [16]:
df.head()

                                                text  emotion
0                            i didnt feel humiliated        0
1  i can go from feeling so hopeless to so damned...        0
2   im grabbing a minute to post i feel greedy wrong        1
3  i am ever feeling nostalgic about the fireplac...        2
4                               i am feeling grouchy        1

In [17]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(df['text'],df['emotion'],
test_size=0.20, random_state=42)

In [18]:
X_train

676      i refers of course though i cant help feeling ...
12113    im starting to feel that im suffering from fat...
7077     i feel like i probably would have liked this b...
13005                  i didn t really feel awkward at all
12123    im feeling a little grumpy today with the lame...
                               ...
13418    i love this because to me it should leave the ...
5390                               i feel is very delicate
860               i was starting to feel a little stressed
15795    i feel stressed tired worn out out of shape or...
7270     i feel that someone is being rude or has wrong...
Name: text, Length: 12800, dtype: object

In [19]:
from sklearn .feature_extraction.text import TfidfVectorizer,CountVectorizer

In [20]:
bow_vectorizer = CountVectorizer()

In [33]:
X_train_bow = bow_vectorizer.fit_transform(X_train)
X_test_bow = bow_vectorizer.transform(X_test)

In [34]:
X_train_bow

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 200058 stored elements and shape (12800, 13501)>

In [35]:
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score

In [36]:
nb_model = MultinomialNB()
nb_model.fit(X_train_bow,y_train)

MultinomialNB()

In [37]:
pred_bow = nb_model.predict(X_test_bow)
print(accuracy_score(y_test,pred_bow))

0.7390625

In [38]:
pred_bow

array([0, 5, 0, ..., 5, 5, 0])

In [39]:
y_test

8756     0
4660     5
6095     0
304      5
8241     0
        ..
15578    5
5746     5
6395     5
7624     5
15245    0
Name: emotion, Length: 3200, dtype: int64

In [42]:
tfidf_vectorizer = TfidfVectorizer()
X_train_tfidf = tfidf_vectorizer.fit_transform(X_train)
X_test_tfidf = tfidf_vectorizer.transform(X_test)

nb2_model = MultinomialNB()
nb2_model.fit(X_train_tfidf,y_train)

MultinomialNB()

In [43]:
y_pred = nb2_model.predict(X_test_tfidf)

In [45]:
print(accuracy_score(y_test,y_pred))

0.6175

In [46]:
from sklearn.linear_model import LogisticRegression

In [47]:
logistic_model = LogisticRegression(max_iter=1000)

In [48]:
logistic_model.fit(X_train_tfidf,y_train)

LogisticRegression(max_iter=1000)

In [49]:
log_pred = logistic_model.predict(X_test_tfidf)

In [50]:
print(accuracy_score(y_test,log_pred))

0.84125